apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
resources:
  - ../../../base/voting
components:
  - ../../../variants/prod/voting
patches:
  - path: version.yaml
  - path: replicas.yaml
