apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendation
spec:
  template:
    spec:
      containers:
        - name: recommendation
          image: ghcr.io/shaversj/craftista/recommendation:sha-18d8e21
