replicas: 1

image:
  repository: ghcr.io/shaversj/craftista/recommendation
<<<<<<< HEAD
  tag: sha-e0f6d50
=======
  tag: latest
>>>>>>> 607c076 (Update helm + workflow)
  pullPolicy: Always

service:
  port: 8082

resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 128Mi
